site_name: Starmadepy Docs
repo_url: https://github.com/DerekRies/starmadepy
site_description: An easy to use python library for starmade game data. Can load starmade template files and allow you to edit them programmatically.